name: build-container
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - HEAD
        include:
          - version: HEAD
            dockerfile: Dockerfile
    steps:
      - id: repository
        run: echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          file: ${{ matrix.dockerfile }}
          build-args: MONAD_VERSION=${{ matrix.version }}
          push: ${{ github.event_name == 'push' }}
          tags: pizzafactory0contorno/${{ steps.repository.outputs.name }}:${{ matrix.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max,scope=${{ matrix.version }}
